1.0.0-SNAPSHOT/main - Avoided multiload of libs has logger and kafve-commons; Implemented logger to kafve-commons

diff --git a/scripts/kafve-commons b/scripts/kafve-commons
--- a/scripts/kafve-commons
+++ b/scripts/kafve-commons
@@ -1,6 +1,34 @@
 #!/usr/bin/env bash
 
-echo "[INFO] Librería kafve_commons cargada correctamente"
+# --- CONFIG --------------------------------------------------------
+# Evitar cargas múltiples.
+[[ ${KAFVE__KAFVE_COMMONS_LOADED+true} ]] && return 0
+
+source "./scripts/logger"
+
+set -o errexit
+set -o errtrace
+set -o nounset
+set -o pipefail
+
+# --- ERROR CONTROL --------------------------------------------------------
+
+# @description Limpia y notifica fallos.
+function catch_error() {
+  	local -r line_number="$1"
+  	local -r script_name="${BASH_SOURCE[1]:-$0}"
+
+  	logger::err "Error en ${script_name}:${line_number}" >&2
+  	logger::err "Comando fallido: '${BASH_COMMAND}'" >&2
+
+	# Funciones de borrado personalizadas dada las funciones
+  	[[ -d "${KAFKA_TEMP_DIR}" ]] && rm -rf "${KAFKA_TEMP_DIR}"
+  	exit 1
+}
+
+trap 'catch_error $LINENO' ERR
+
+# --- FUNCTIONS -----------------------------------------------------------
 
 # @description Normaliza una ruta eliminando basura de Windows, comillas y espacios.
 #              Si detecta Windows, convierte la ruta al formato Unix (Cygwin/MSYS).
@@ -42,3 +70,6 @@ kafve_commons::get_kafka_script() {
     # Limpiar el path si empieza con ./ para que se vea más estético
     echo "${full_path}"
 }
+
+# Establece que la librería KAFVE__KAFVE_COMMONS_LOADED
+readonly KAFVE__KAFVE_COMMONS_LOADED=true
