1.0.0-SNAPSHOT/main - Added to kafve-consumer script configuration with error control; Replaced echo by logger lib

diff --git a/scripts/kafve-consumer b/scripts/kafve-consumer
--- a/scripts/kafve-consumer
+++ b/scripts/kafve-consumer
@@ -1,4 +1,27 @@
 #!/usr/bin/env bash
+# --- CONFIG --------------------------------------------------------
+source "./scripts/logger"
+
+set -o errexit
+set -o errtrace
+set -o nounset
+set -o pipefail
+
+# --- ERROR CONTROL --------------------------------------------------------
+
+# @description Limpia archivos temporales y notifica fallos en el script.
+# @param $1 string Número de línea donde ocurrió el error.
+consumer::catch_error() {
+	local -r line_number="$1"
+	local -r script_name="${BASH_SOURCE[1]:-$0}"
+
+	logger::err "Error en ${script_name}:${line_number}" >&2
+	logger::err "Comando fallido: '${BASH_COMMAND}'" >&2
+
+	exit 1
+}
+
+trap 'consumer::catch_error $LINENO' ERR
 
 # --- VARS -------------------------------------------------------------------------------------------------------------
 readonly KAFKA_CONSUMER_CLASS="org.apache.kafka.tools.consumer.ConsoleConsumer"
@@ -35,7 +58,7 @@ consumer::main() {
 			shift 2
 			;;
 		*)
-			echo "[SKIP] ./kafve consumer <comando> [argumentos]"
+			logger::custom "SKIP" "./kafve consumer <comando> [argumentos]"
 			return 0
 			;;
 		esac
@@ -68,24 +91,24 @@ consumer::start() {
 	local -r log_file="${KAFVE_LOG_DIR}/consumer-${topic}.log"
 	local consumer_pid
 
-	echo "[RUN] Inicializando consumidor para el tópico: ${topic}"
+	logger::run "Inicializando consumidor para el tópico: ${topic}"
 
 	### Comprueba si ya se ha arrancado un consumer en el tópico
 	if consumer::is_running "${topic}"; then
-		echo "[ERROR] Ya existe un consumer para el tópico: ${topic}"
+		logger::err "Ya existe un consumer para el tópico: ${topic}"
 		exit 0
 	fi
 
 	### Comprueba si existe una carpeta de logs, sino la crea
 	if [[ ! -d "${KAFVE_LOG_DIR}" ]]; then
 		mkdir -p "${KAFVE_LOG_DIR}"
-		echo " -[OK] Carpeta de logs '${KAFVE_LOG_DIR}' creada correctamente."
+		logger::ok "Carpeta de logs '${KAFVE_LOG_DIR}' creada correctamente."
 	fi
 
 	### Comprueba si se ha quedado un consumer.log residual y lo elimina
 	if [[ -f "${log_file}" ]]; then
 		rm -f "${log_file}"
-		echo " -[OK] Borrado archivo residual del anterior consumer del mismo tópico"
+		logger::ok "Borrado archivo residual del anterior consumer del mismo tópico"
 	fi
 
 	### Inicializa el consumer en segundo plano
@@ -103,11 +126,11 @@ consumer::start() {
 	### Comprueba que se ha inicializado correctamente
 	sleep 1
 	if ps -p "${consumer_pid}" >/dev/null; then
-		echo "[DONE] Consumidor del tópico '${topic}' iniciado en segundo plano."
-		echo "[DONE] Logs disponibles en: ${log_file} (PID: ${consumer_pid})"
+		logger::done "Consumidor del tópico '${topic}' iniciado en segundo plano."
+		logger::done "Logs disponibles en: ${log_file} (PID: ${consumer_pid})"
 		return 0
 	else
-		echo "[ERROR] El consumidor falló al arrancar. Revisa ${log_file} para más detalles."
+		logger::err "El consumidor falló al arrancar. Revisa ${log_file} para más detalles."
 		return 1
 	fi
 }
@@ -118,21 +141,21 @@ consumer::info() {
 	local -r topic="$1"
 	local -r log_file="${KAFVE_LOG_DIR}/consumer-${topic}.log"
 
-	echo "[RUN] Abriendo visor de logs para el consumer en tiempo real..."
+	logger::run "Abriendo visor de logs para el consumer en tiempo real..."
 
 	### Comprueba si está arrancado el consumer para el topic
 	if ! consumer::is_running "${topic}"; then
-		echo "[ERROR] No existe un consumer para el tópico: ${topic}"
-		exit 0
+		logger::err "No existe un consumer para el tópico: ${topic}"
+		return 1
 	fi
 
 	### Comprueba si existe el log para visualizar
 	if [[ ! -f "${log_file}" ]]; then
-		echo " -[ERROR] No se ha encontrado el archivo de log: ${log_file}"
+		logger::err "No se ha encontrado el archivo de log: ${log_file}"
 		return 1
 	fi
 
-	trap 'echo -e "\n[DONE] Has salido del visor de logs del consumer"; trap - INT; return' INT
+	trap 'printf "\n"; logger::done "Has salido del visor de logs del consumer"; trap - INT; return' INT
 	tail -f "${log_file}"
 
 	### Limpiamos la trap al salir para no afectar al resto del script
@@ -146,7 +169,7 @@ consumer::stop() {
 	local -r log_file="${KAFVE_LOG_DIR}/consumer-${topic}.log"
 	local pid
 
-	echo "[RUN] Deteniendo consumidor del tópico '${topic}'"
+	logger::run "Deteniendo consumidor del tópico '${topic}'"
 
 	### Buscamos el pid del consumer para el tópico (Se quitó el redireccionamiento incorrecto del subshell)
 	# shellcheck disable=SC2009
@@ -159,28 +182,28 @@ consumer::stop() {
 		### Verificamos si realmente murió
 		sleep 2
 		if ps -p "${pid}" >/dev/null 2>&1; then
-			echo " -[WARN] No cerró a tiempo, forzando parada..."
+			logger::warn "No cerró a tiempo, forzando parada..."
 			kill -9 "${pid}"
-			echo " -[OK] Consumidor detenido forzando la parada."
+			logger::ok "Consumidor detenido forzando la parada."
 		fi
 
 		### Elimina el archivo de log como parte del proceso de parada y limpieza
 		if [[ -f "${log_file}" ]]; then
 			rm -f "${log_file}"
-			echo " -[OK] Borrado archivo de log del consumer"
+			logger::ok "Borrado archivo de log del consumer"
 		fi
 
-		echo "[DONE] Consumidor detenido."
+		logger::done "Consumer con el PID: ${pid}, ha detenido."
 		return 0
 	else
-		echo "[ERROR] No se encontró ningún consumidor activo para el tópico '${topic}'."
+		logger::err "No se encontró ningún consumidor activo para el tópico '${topic}'."
 		return 1
 	fi
 }
 
 # @description Muestra por pantalla una tabla con todos los consumidores de Kafka activos.
 consumer::status() {
-	echo "[RUN] Consultando estado de los Consumers..."
+	logger::run "Consultando estado de los Consumers..."
 
 	echo "-------------------------------------------------------------------------------------------"
 	printf "| %-8s | %-22s | %-8s | %-40s |\n" "PID" "TOPIC" "TIME" "BROKER URL"
@@ -192,7 +215,7 @@ consumer::status() {
 	done
 	echo "-------------------------------------------------------------------------------------------"
 
-	echo "[DONE] Consulta de estado finalizada."
+	logger::done "Consulta de estado finalizada."
 }
 
 # @description Procesa una línea de comando de proceso de consumidor y la imprime formateada en la tabla.
@@ -224,7 +247,5 @@ consumer::is_running() {
 	fi
 }
 
-################################################################################
-#                               MAIN RUN                                       #
-################################################################################
+# --- MAIN RUN -----------------------------------------------------------
 consumer::main "$@"
